print("www.Learn Python.com")
print("Hello, World!")
print("This is my first program.")
print("I am learning Python.")
print("Python is easy to learn.")
print("Python is a powerful language.")
print("Python is used for web development, AI, and data science.")
print("Python is a high-level language.")
print("Python is an interpreted language.")
print("Python is an object-oriented language.")
print("Python is a general-purpose language.")
print("Python is a dynamically-typed language.")
print("Python is a beginner-friendly language.")
print("Python is a versatile language.")
print("Python is a popular language.")
print("Python is a free language.")
print("Python is a cross-platform language.")
print("Python is a community-driven language.")
print("Python is a secure language.")
print("Python is a fast language.")
print("Python is a scalable language.")
print("Python is a robust language.")
print("Python is a stable language.")
print("Python is a mature language.")
print("Python is a powerful language.")
print("Python is a versatile language.")
print("Python is a general-purpose language.")
print("Python is a high-level language.")
print("Python is a dynamically-typed language.")
print("Python is an interpreted language.")
print("Python is an object-oriented language.")
print("Python is a beginner-friendly language.")
print("Python is a popular language.")
